// Optimized WebP variants (~90% smaller). Generated by `npm run optimize:images`.
import advertisingImg from '@/assets/products/navbar/advertising.webp';
import eventsImg from '@/assets/products/navbar/events.webp';
import sportsImg from '@/assets/products/navbar/sports.webp';
import virtualProductionImg from '@/assets/products/navbar/virtual-production.webp';
import corporateImg from '@/assets/products/navbar/corporate.webp';
import controlRoomsImg from '@/assets/markets/control-rooms-detail.jpg';

export interface MarketDetail {
  slug: string;
  title: string;
  tag: string;
  heroImage: string;
  headline: string;
  keySpecs: { label: string; value: string }[];
  differentiators: string[];
  recommendedSolutions: { name: string; slug: string; category: string; image: string; fitReason: string }[];
  typicalProjects: { title: string; image: string }[];
  ctaTitle: string;
  ctaDescription: string;
}

const markets: Record<string, MarketDetail> = {
  sports: {
    slug: 'sports',
    title: 'Sports & Arenas',
    tag: 'Stadium-Grade LED',
    heroImage: sportsImg,
    headline: 'High-brightness LED displays built for open-air stadiums and indoor arenas, delivering clear visuals to every seat.',
    keySpecs: [
      { label: 'Brightness', value: '5,000 – 7,000 nits' },
      { label: 'Pixel Pitch', value: 'P6 – P10' },
      { label: 'Protection', value: 'IP65 Front & Rear' },
    ],
    differentiators: [
      '5,000+ nit panels visible in direct sunlight without glare',
      '160° horizontal viewing angle covers sideline seating to upper tiers',
      '3,840Hz+ refresh rate eliminates flicker on broadcast cameras',
      'Modular cabinets with front and rear service access',
    ],
    recommendedSolutions: [
      { name: 'LED Screen', slug: 'led-screen', category: 'led-screen', image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&h=400&fit=crop', fitReason: 'High-brightness outdoor panels for perimeter and scoreboard displays' },
      { name: 'Wash Light', slug: 'wash-light', category: 'wash-light', image: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=600&h=400&fit=crop', fitReason: 'Wide-beam wash lighting for arena architecture and tunnel effects' },
    ],
    typicalProjects: [
      { title: 'Premier League Stadium Perimeter', image: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=800&h=450&fit=crop' },
      { title: 'Multi-Purpose Indoor Arena', image: 'https://images.unsplash.com/photo-1504450758481-7338eba7524a?w=800&h=450&fit=crop' },
    ],
    ctaTitle: 'Plan Your Venue Display',
    ctaDescription: 'Talk to our team about LED and lighting solutions designed for your stadium or arena.',
  },
  advertising: {
    slug: 'advertising',
    title: 'Advertising & DOOH',
    tag: 'Digital Out-of-Home',
    heroImage: advertisingImg,
    headline: 'High-brightness digital displays for billboards, transit shelters, and urban advertising networks that run 24/7.',
    keySpecs: [
      { label: 'Brightness', value: '6,000 – 10,000 nits' },
      { label: 'Pixel Pitch', value: 'P4 – P10' },
      { label: 'Protection', value: 'IP65 / IP66' },
    ],
    differentiators: [
      'Auto-brightness sensors adapt to ambient light in real time',
      'Common cathode drivers reduce power consumption by up to 40%',
      'Remote monitoring and content management via cloud platform',
      'Vandal-resistant front panels with anti-reflective coating',
    ],
    recommendedSolutions: [
      { name: 'LED Screen', slug: 'led-screen', category: 'led-screen', image: advertisingImg, fitReason: 'High-brightness outdoor panels purpose-built for billboard and facade applications' },
    ],
    typicalProjects: [
      { title: 'Urban Digital Billboard Network', image: advertisingImg },
      { title: 'Shopping Mall Facade Display', image: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=800&h=450&fit=crop' },
    ],
    ctaTitle: 'Start Your DOOH Project',
    ctaDescription: 'Get specifications and pricing for outdoor advertising displays built for continuous operation.',
  },
  events: {
    slug: 'events',
    title: 'Events & Staging',
    tag: 'Touring & Rental LED',
    heroImage: eventsImg,
    headline: 'Lightweight, rapid-deploy LED systems for concerts, corporate events, and touring productions.',
    keySpecs: [
      { label: 'Panel Weight', value: '7 – 15 kg/m²' },
      { label: 'Pixel Pitch', value: 'P2.6 – P3.9' },
      { label: 'Setup Time', value: 'Tool-Free Locks' },
    ],
    differentiators: [
      'Die-cast aluminum cabinets with tool-free quick-lock assembly',
      'Curved configurations from -10° to +15° for creative stage designs',
      'Front-service magnetic modules for hot-swapping during shows',
      '500×500mm and 500×1000mm unified platforms for mixed splicing',
    ],
    recommendedSolutions: [
      { name: 'LED Screen', slug: 'led-screen', category: 'led-screen', image: eventsImg, fitReason: 'Rental-grade LED panels for stage backdrops and IMAG screens' },
      { name: 'Moving Heads', slug: 'moving-heads', category: 'moving-heads', image: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=600&h=400&fit=crop', fitReason: 'DMX-controlled moving heads for dynamic stage lighting effects' },
      { name: 'Wash Light', slug: 'wash-light', category: 'wash-light', image: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=600&h=400&fit=crop', fitReason: 'Wide-coverage wash fixtures for stage and audience lighting' },
    ],
    typicalProjects: [
      { title: 'Concert Tour Stage Design', image: eventsImg },
      { title: 'Corporate Product Launch', image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&h=450&fit=crop' },
    ],
    ctaTitle: 'Plan Your Event Display',
    ctaDescription: 'Talk to our rental team about LED and lighting packages for your next production.',
  },
  'virtual-production': {
    slug: 'virtual-production',
    title: 'Virtual Production',
    tag: 'XR & VP LED Volumes',
    heroImage: virtualProductionImg,
    headline: 'High-resolution LED volumes for in-camera VFX, broadcast studios, and XR content creation.',
    keySpecs: [
      { label: 'Pixel Pitch', value: 'P1.2 – P2.6' },
      { label: 'Refresh Rate', value: '7,680 Hz' },
      { label: 'Brightness', value: '800 – 1,200 nits' },
    ],
    differentiators: [
      'Sub-frame latency compatible with real-time camera tracking systems',
      '16-bit color processing with HDR support for accurate in-camera capture',
      'Moiré-free panel design optimized for cinema camera sensors',
      'Genlock and frame-sync support for broadcast and film workflows',
    ],
    recommendedSolutions: [
      { name: 'LED Screen', slug: 'led-screen', category: 'led-screen', image: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=600&h=400&fit=crop', fitReason: 'Fine-pitch LED panels for LED volumes and virtual production stages' },
      { name: 'Puck Lights', slug: 'puck-lights', category: 'puck-lights', image: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=600&h=400&fit=crop', fitReason: 'Compact accent lighting for set elements and practicals' },
    ],
    typicalProjects: [
      { title: 'Film Studio LED Volume', image: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800&h=450&fit=crop' },
      { title: 'Broadcast News Studio', image: 'https://images.unsplash.com/photo-1605810230434-7631ac76ec81?w=800&h=450&fit=crop' },
    ],
    ctaTitle: 'Design Your VP Stage',
    ctaDescription: 'Work with our specialists to specify an LED volume for your production requirements.',
  },
  corporate: {
    slug: 'corporate',
    title: 'Corporate & Control Rooms',
    tag: 'Mission-Critical Displays',
    heroImage: corporateImg,
    headline: 'Seamless LED video walls for control rooms, boardrooms, and 24/7 operations centers.',
    keySpecs: [
      { label: 'Pixel Pitch', value: 'P0.9 – P1.8' },
      { label: 'Brightness', value: '300 – 600 nits' },
      { label: 'Technology', value: 'COB / MIP' },
    ],
    differentiators: [
      'True seamless design with zero visible bezels between cabinets',
      'Front-maintenance magnetic modules for restricted-access installs',
      'Auto-calibration maintains color uniformity across the wall over time',
      'Calibrated to 300–600 nits for comfortable 24/7 viewing',
    ],
    recommendedSolutions: [
      { name: 'LED Screen', slug: 'led-screen', category: 'led-screen', image: controlRoomsImg, fitReason: 'Fine-pitch COB LED panels for close-viewing control room applications' },
      { name: 'Puck Lights', slug: 'puck-lights', category: 'puck-lights', image: corporateImg, fitReason: 'Discrete architectural lighting for corporate lobbies and meeting rooms' },
    ],
    typicalProjects: [
      { title: 'Network Operations Center', image: controlRoomsImg },
      { title: 'Executive Boardroom', image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=450&fit=crop' },
    ],
    ctaTitle: 'Specify Your Display Wall',
    ctaDescription: 'Consult with our team on fine-pitch LED solutions for your control room or corporate space.',
  },
};

export function getMarketDetail(slug: string): MarketDetail | null {
  return markets[slug] || null;
}

export function getAllMarketSlugs(): string[] {
  return Object.keys(markets);
}
